version: '3'

services:
  bot:
    build: .
    command: python main.py
    volumes:
      - .:/app
    depends_on:
      - web
    env_file:
      - .env

  web:
    build: .
    command: python main.py web
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .env